### PR TITLE
Changed default port. Added logic to start app in browser

### LINKED ISSUE #19: Issue starting iSDI server on MacOS Monterey
By default, the current latest version of MacOS (Monterey) listens on port 5000 due to the new AirPlay functionality. This prevents isdi from being launched when run. 

Workaround is to disable AirPlay by turning off "Airplay Receiver" in the "Sharing" System Preference. 

Error:
```
TEST=False
Creating new db connection /Users/adil/Documents/IPV/isdi/data/fieldstudy.db
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "./isdi", line 26, in <module>
    app.run(host="0.0.0.0", port=PORT, debug=config.DEBUG)
  File "/Users/adil/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/Users/adil/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 48] Address already in use
```

Checking running ports shows Control Center listening at ports 5000 and 7000.

```(base) xxxx@xxxxx-MacBook-Air isdi % sudo lsof -nP -iTCP -sTCP:LISTEN
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
---
adb       1676 xxxx    9u  IPv4 0xb21b2473ff6d05a9      0t0  TCP 127.0.0.1:5037 (LISTEN)
iproxy    1730 xxxx    3u  IPv4 0xb21b2474004b7b09      0t0  TCP 127.0.0.1:2222 (LISTEN)
iproxy    1730 xxxx    4u  IPv6 0xb21b24740bfe8151      0t0  TCP [::1]:2222 (LISTEN)
ControlCe 2288 xxxx   48u  IPv4 0xb21b247420213069      0t0  TCP *:7000 (LISTEN)
ControlCe 2288 xxxx   49u  IPv6 0xb21b24740bfe8f11      0t0  TCP *:7000 (LISTEN)
ControlCe 2288 xxxx   50u  IPv4 0xb21b24740f82a589      0t0  TCP *:5000 (LISTEN)
ControlCe 2288 xxxx   51u  IPv6 0xb21b24740bfe95f1      0t0  TCP *:5000 (LISTEN)
```

Disabling AirPlay receiver on MacOS fixes the issue, but the permanent fix would be to change the iSDI port number.

Ref: https://developer.apple.com/forums/thread/682332

### PR DESCRIPTION
**Pull request by adilahmed31**
- Updated installation steps for Ubuntu (Verified on Ubuntu 20.04). Changed port number in instructions.
- Changed port number from 5000 to 6200.
- Added logic to start browser automatically (disabled when running in DEBUG mode). It can be made to work in debug mode by simply disabling Flask's auto reloader by setting app.run(use_reloader=False) . Otherwise the browser tab is opened twice if run in debug mode.

Resolves #19

### CODE REVIEW

**Review by rchatterjee — APPROVED** [review]
The browser window does not open in WSL, but I guess that is fine. It does not break anything in WSL. 👍

**Review by grantv9 — CHANGES_REQUESTED** [review]
The new port worked on macOS but the browser did not open for me either. Let's solve that before merging but otherwise the changes are good

**Comment by adilahmed31** [comment]
> The new port worked on macOS but the browser did not open for me either. Let's solve that before merging but otherwise the changes are good

The browser open is disabled when run in DEBUG mode, which is the default currently. 
Flask runs an auto reloader in debug mode, which is used to automatically relaunch the app when any code change occurs while the app is running.  This causes the browser tab to open twice in debug mode so i disabled it. 

If we disable this auto reload, it should work pretty smoothly. If we want to keep it, there are some hacky solutions / workarounds. Are we okay with disabling the auto reload?

**Comment by grantv9** [comment]
> The browser open is disabled when run in DEBUG mode, which is the default currently

I wasn't running in debug mode (aka ran `TEST=0 ./isdi`), and the browser didn't open for some reason.

> Are we okay with disabling the auto reload?

Given that test mode is being removed in #32, I think we can ignore the situation where the browser tab is opened twice. Ultimately the port functionality works, so I'm fine approving this.

**Review by grantv9 — APPROVED** [review]
The new port works as expected. I'm not seeing the browser open either, but I'm fine approving the changes

**Comment by adilahmed31** [comment]
> The new port works as expected. I'm not seeing the browser open either, but I'm fine approving the changes

Great! I had put in a one line flag to disable the browser open in some modes. I've removed it and it should work perfectly now irrespective of which mode it's run in

**Review by grantv9 — APPROVED** [review]
The browser loading worked in normal mode. LGTM 👍

**Pull request merged**
