### PR TITLE
Remove use of deprecated readPList() 

### PR DESCRIPTION
**Pull request by shffrror**
This was a blocker for using Python versions over 3.8, verified this works with Python 3.9

### CODE REVIEW

**Comment by rchatterjee** [comment]
Someone with iPhone has to review this. @lanamorgan @grantv9.

**Comment by grantv9** [comment]
I can try testing this evening. Should I use python 3.8 or 3.9?

**Comment by rchatterjee** [comment]
Try 3.9, if it complains for that one issue of on_bad_lines, just modify to test. 
Refer to this for fixing that one line incompatibility bug: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html.

**Comment by grantv9** [comment]
I just tried with python 3.9.10 with an iPhone and got the bad_lines error.

`FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.`

`APP_FLAGS = pd.read_csv(`

I also got the same error as #19, but I'm not sure if that's related.

**Comment by rchatterjee** [comment]
Can you change `error_bad_lines=False` to `on_bad_lines="skip"`, and check if the rest of the changes work? If so, merge the PR. This issue will be fixed once we merge all the outstanding PRs.

**Comment by grantv9** [comment]
Making that change in `parse_dump.py`, `blocklist.py`, and `app_flags_patch.py` resolved the bad_lines error. I'm unable to fully verify functionality with my iPhone due to the #19 bug but otherwise this looks good to me

**Comment by lanamorgan** [comment]
Checked and also looks good to me; didn't encounter airplay bug so I think this can be merged in!

**Pull request merged**
