### PR TITLE
Cleaning up 1: Removing all statically linked libraries

### PR DESCRIPTION
**Pull request by rchatterjee**
Also removed certain scripts that we will not need for the functionality of ISDi.

### CODE REVIEW

**Comment by tomrist** [comment]
Should we also remove  report_failure.md? Doesn't seem used anywhere

**Comment by rchatterjee** [comment]
Yeah, true. We can do that. Updating the PR.

**Comment by tomrist** [comment]
Same question for the file in phone_dumps/ . Is this being used for testing? It didn't come up in a grep, though perhaps used via a script?

**Comment by tomrist** [comment]
isdi/logs has a typo in name: .dumy

**Comment by rchatterjee** [comment]
Yeah, `phone_dumps/` is used to dump the apks from the phone for further
analysis.

**Comment by tomrist** [comment]
Did we want to remove the other file in phone_dumps though? Do we need it as an example?

**Comment by shffrror** [comment]
@rchatterjee It looks like there are a couple conflicts, if you want to resolve I can pull locally and test.

**Comment by rchatterjee** [comment]
Yeah, fixed the conflicts.

**Comment by shffrror** [comment]
@rchatterjee Confirmed functioning on iPhone XR with IOS 15.2.1. There were issues with the blocklist file and the `~test` preface but I believe those are known?

**Review by shffrror — APPROVED** [review]

**Pull request merged**
